CREATE TABLE IF NOT EXISTS `#__invoice` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '1',
  `releaseDate` int(11) NOT NULL,
  `sellDate` int(11) NOT NULL,
  `paymentDate` int(11) NOT NULL,
  `number` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `contractor` int(11) NOT NULL,
  `detailsSeller` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `buyerName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `buyerCountry` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `buyerCity` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `buyerPostCode` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `buyerStreet` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `buyerNIP` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `shipmentName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `shipmentCountry` varchar(127) COLLATE utf8_unicode_ci NOT NULL,
  `shipmentCity` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `shipmentPostCode` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `shipmentStreet` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `showShipment` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `headline` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` tinyint(1) NOT NULL,
  `correctionNumber` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `correctionDate` int(11) NOT NULL,
  `correctionReason` text COLLATE utf8_unicode_ci NOT NULL,
  `valueNett` double NOT NULL,
  `valueGross` double NOT NULL,
  `owner` int(11) NOT NULL,
  `created` int(11) NOT NULL,
  `modified` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;
